### ISSUE TITLE
SQL — продвинутый уровень Q7

### ISSUE THREAD

**Issue by alexsis71** [Londeren/hh-skill-verifications-quizzes#10]
Я вот тут не вдуплил... Это вот они реально?

Q7. Вам нужно создать представление с именем PeopleView с данными из двух таблиц Respondents и Info, в котором будут содержаться возраст, телефоны и адреса респондентов. Какая ошибка допущена в запросе?
CREATE VIEW PeopleView 
AS SELECT age, phone_number, address 
FROM Respondents, Info
WHERE Respondents.respondent_id = Info.respondent_id;

 Не нужно указывать обе таблицы в строке с FROM

**Comment by Londeren** [comment]
Может и нет, в тесте 13 правильных из 15) 
Если ты прошел тест, дал тут другой ответ и получил 14 из 15, то я с радостью приму твой PR в этом вопросе))

**Comment by alexsis71** [comment]
Не, 12 из 15. Но я сам отвечал. Потом просто стпл ради интереса искать. Я здесь ответил что в select надо имена таблиц - select Respondents.age, ... Потому что phone_number есть в обеих таблицах. И это явная ошибка. 

Одна ошибка у меня точно с q9 SET XACT_ABORT, NOCOUNT ON
Вторая - q6 с MEDIAN. Q9 - это сугубо SQL Server, о чем они не предупреждают  Q6 - это оракл, и того и другого, люди работающие например с постгресом, вообще могут не знать. А вот третья в q5, там промахнулся, ткнул пальцем не туда. У тебя эти ответы походу точно правильные. Так что с q7, думаю все таки не этот ответ

**Comment by Londeren** [comment]
Благодарю, я перепроверю и поправлю ответ)

**Comment by Londeren** [comment]
Проверил и поправил, теперь 14 правильных
